:imagesdir: ../assets/images

== Container Service Files

Now we’ll create the service configuration files, also known as
`+systemd unit+` files. These files are plain text ini-style files that
encode information about the podman container that we want to run as a
rootless service.

In other words, we will log into a non-root user account on our RHEL
system and configure a service to run a docker container with Podman.

There are many types of Podman systemd unit files, including container,
volume, and network (to name a few). The container unit file contains
configuration information about how the docker container should by run
by Podman, including where to obtain the image, how to map persistent
volumes, and what ports to expose for incoming client connections. For
more information, please refer to the Podman
https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html[documentation
here].

== Create the configuration directory

In the terminal we are logged in as the user `+rhel+`. `+rhel+`
is not a privileged user.

We’ll create a directory in `+rhel+`’s home directory to store our
unit files. The unit files will be stored in
`+/home/rhel/.config/containers/systemd/+`.

Run the command below by clicking on the `+run+` button.

[source,bash,run]
----
mkdir -p ~/.config/containers/systemd/
----

== Create the unit files

We will create two unit files. 1) `+httpd.container+` 2)
`+httpd-data.volume+`

Run the command below, by clicking on the run button, to create the
`+httpd.container+` file.

[source,bash,run]
----
touch ~/.config/containers/systemd/httpd.container
----

Run the command below to create the `+httpd-data.volume+` file.

[source,bash,run]
----
touch ~/.config/containers/systemd/httpd-data.volume
----

We’ll configure these files and discuss their purpose in the next
assignment. Click next to proceed.
